//
//  Recipes.swift
//  wwdc
//
//  Created by Michelle Han on 2/22/24.
//

import Foundation

import SwiftUI

let japanIngredients = [
    Ingredient(name: "Cabbage", imageName: "cabbage", imager: "cabbager", info: "A leafy green, red, or white biennial plant grown as an annual vegetable crop for its dense-leaved heads.", culture: "Cultivated for thousands of years in Europe and Asia, cabbage is a staple in many cuisines, including Eastern European, Asian, and Irish.", mapImage: "cabbagem", nutr: "Rich in vitamins K, C, and B6, and a good source of dietary fiber, cabbage supports digestive health and immune function.", recAndUse: "Used in a variety of dishes, from fermented foods like sauerkraut and kimchi to salads, soups, and stews.", vitamins: ["Vitamin K", "Vitamin C", "Vitamin B6"]),
    Ingredient(name: "Flour", imageName: "flour", imager: "flourr", info: "A powder obtained by grinding raw grains, roots, beans, nuts, or seeds, flour is a fundamental ingredient in baking and cooking.", culture: "Flour has been a basic food ingredient since prehistoric times, with wheat flour being the most common type used in Western countries.", mapImage: "flourm", nutr: "Primarily composed of carbohydrates, but whole wheat flour is also a source of protein and dietary fiber.", recAndUse: "Essential for baking bread, cakes, and pastries, flour is also used for thickening sauces and coating foods before frying.", vitamins: ["Carbohydrates", "Protein", "Fiber"]),
    Ingredient(name: "Eggs", imageName: "eggs", imager: "eggsr", info: "Eggs are laid by female animals of many different species and are a common food ingredient worldwide.", culture: "Domesticated in Southeast Asia and India around 3200 BCE, chicken eggs are a global staple, symbolizing fertility and rebirth in many cultures.", mapImage: "eggsm", nutr: "A great source of protein, vitamins, and minerals, eggs contain high-quality protein and healthy fats.", recAndUse: "Versatile in cooking, used in baking, making omelets, poached, scrambled, or boiled.", vitamins: ["Protein", "Vitamin D", "Vitamin A"]),
    Ingredient(name: "Pork Belly", imageName: "porkbelly", imager: "porkbellyr", info: "A boneless cut of fatty meat from the belly of a pig, pork belly is prized for its flavor and tenderness.", culture: "Widely used in Asian and European cuisines, it's the main ingredient in dishes like bacon, pancetta, and Korean samgyeopsal.", mapImage: "pbm", nutr: "High in fat, it's also a good source of protein, vitamins, and minerals, particularly when consumed in moderation.", recAndUse: "Can be roasted, smoked, or fried, and is often used to add depth to soups and stews or served crisped as a main dish.", vitamins: ["Fat", "Protein", "Vitamin B"]),
    Ingredient(name: "Bonito Flakes", imageName: "flakes", imager: "flakesr", info: "Thinly shaved flakes of dried, fermented, and smoked skipjack tuna, known for their umami flavor.", culture: "Originating from Japan, bonito flakes are a key ingredient in traditional Japanese cuisine, used to make dashi stock.", mapImage: "japanmap", nutr: "Low in calories but high in protein and rich in omega-3 fatty acids and other beneficial nutrients.", recAndUse: "Essential for dashi broth, they're also used as a topping for okonomiyaki, takoyaki, and other Japanese dishes.", vitamins: ["Protein", "Omega-3"]),
    Ingredient(name: "Green Onion", imageName: "green-onion", imager: "greenonionsr", info: "Also known as scallions or spring onions, these are young shoots of onions harvested before the bulb has enlarged.", culture: "Used worldwide, they have been a part of Chinese cuisine for thousands of years and are featured in many Asian, American, and European dishes.", mapImage: "worldmap", nutr: "Rich in vitamins A and C, calcium, and iron, green onions add a nutritional boost to dishes.", recAndUse: "Commonly used as a garnish, in salads, soups, and noodle dishes, adding a fresh, mild onion flavor.", vitamins: ["Vitamin K", "Vitamin C", "Vitamin A"]),
    Ingredient(name: "Soy Sauce", imageName: "soy-sauce", imager: "soysaucer", info: "A liquid condiment of Chinese origin, made from fermented soybeans, roasted grain, water, and salt.", culture: "With a history dating back over 2,500 years in East Asia, soy sauce is an essential seasoning in many Asian cuisines.", mapImage: "china", nutr: "Contains amino acids, vitamins, and minerals, though it's high in sodium.", recAndUse: "Used as a marinade, seasoning, and dipping sauce, it adds a savory umami flavor to a wide range of dishes.", vitamins: ["Sodium"])
]
